
 ----------
#2. **Define the trigger events**: Specify the events that will trigger the workflow.
 
   ```yaml
   on:
     push:
       branches:
         - main
     pull_request:
       branches:
         - main
   ```
 
#3. **Define jobs**: Translate your CircleCI jobs to GitHub Actions jobs. Here’s a simple example:
 
   **CircleCI job:**
   ```yaml
   jobs:
     build:
       docker:
         - image: circleci/node:12
       steps:
         - checkout
         - run: npm install
         - run: npm test
   ```
 
   **GitHub Actions equivalent:**
   ```yaml
   jobs:
     build:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v2
         - name: Set up Node.js
           uses: actions/setup-node@v2
           with:
             node-version: '12'
         - run: npm install
         - run: npm test
   ```
   ----------
 
