version: 2.1
jobs:
  test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run:
          name: Run tests
          command: touch tests.txt && false
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run:
          name: Build an artifact
          command: touch build.txt
      - store_artifacts:
          path: build.txt
  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run:
          name: deploy
          command: ./deploy.sh
